services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ric
    ports:
      - "5432:5432"
    volumes:
      - ric_pgdata:/var/lib/postgresql/data
      - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./backend/db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/ric?sslmode=disable
      PORT: 8080
      CORS_ORIGINS: "*"
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  ric_pgdata:
